"""empty message

Revision ID: 379ff2e91076
Revises: a34b0520b5b3
Create Date: 2018-02-24 11:18:04.434971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379ff2e91076'
down_revision = 'a34b0520b5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_type', sa.String(length=20), nullable=True))
    op.drop_index('ix_employees_username', table_name='employees')
    op.drop_column('employees', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.create_index('ix_employees_username', 'employees', ['username'], unique=True)
    op.drop_column('employees', 'user_type')
    # ### end Alembic commands ###
